version: "3"
services:
  telegram-get:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PUID=1000 # 宿主机用户pid
      - PGID=1000 # 宿主机用户gid
    volumes:
      - ./data_online:/workdir/data_online
      - ./logs:/workdir/logs
    restart: unless-stopped