version: "3"
services:
  telegram-get:
    image: 520xcy/telegram-get:latest
    environment:
      - PUID=1000 # 宿主机用户pid
      - GUID=1000 # 宿主机用户gid
    volumes:
      - 下载的目录:/workdir/data_online
      - 日志目录:/workdir/logs
    restart: unless-stopped